run-name: Build repository kovacsmiki with list _all.
on:
  schedule:
    - cron: "0 8 * * 6"
  workflow_dispatch:

permissions: write-all

jobs:
  build-package-list:
    uses: ./.github/workflows/build.yml
    with:
      target_name: _all
    secrets: inherit
  build-repository:
    runs-on: ubuntu-latest
    needs: build-package-list
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v8
        with:
          name: ${{ needs.build-package-list.outputs.artifact_name }}
          path: ./package_files
      - run: chmod 777 ./package_files
      - run: |
          echo "repo-add /data/kovacsmiki.db.tar.zst /data/*.pkg.tar.zst" > script.sh
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
          docker run --rm --pull always -t -v $(pwd)/package_files:/data:rw -v $(pwd)/script.sh:/script.sh ghcr.io/mortyr45/pacman-repository:latest bash /script.sh
      - run: |
          cd ./package_files
          rm kovacsmiki.{db,files}
          mv kovacsmiki.db.tar.zst kovacsmiki.db
          mv kovacsmiki.files.tar.zst kovacsmiki.files
          cd -
      - uses: Hs1r1us/Release-AIO@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: ${{ github.sha }}
          asset_files: ./package_files
          draft: ${{ github.event_name != 'schedule' }}
