name: Build container
run-name: Build and push container to ghcr.io.
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */8 * * *"
permissions:
  packages: write
jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
